version: '2.3'

services:
  silero:
    restart: always
    container_name: silero
    build:
      context: .
      dockerfile: Dockerfile
    #runtime: nvidia
    image: silero:master
    volumes:
      - .:/silero
    ports:
      - 8899:8899
