version: '2.3'

services:
  silero:
    restart: always
    container_name: silero
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #runtime: nvidia
    image: aspichakou/silero
    volumes:
      - .:/silero
    ports:
      - 8899:8899
